// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzfaogzltieoagqgjfps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZmFvZ3psdGllb2FncWdqZnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MTgzNjYsImV4cCI6MjA3NTA5NDM2Nn0.vNglfBRB_ddxiLF0Y3DLoUP5HjQZ6rs4fN1F3UFoVcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});